FROM python:3.10-alpine AS unit_tests
WORKDIR /srv
COPY ./analysis /srv/analysis
COPY ./tests /srv/tests
RUN python -m unittest tests/test_analysis.py

FROM python:3.10-alpine
WORKDIR /srv
COPY --from=unit_tests /srv/tests /srv
