version: "3"
services:

  analysis:
    build: ./analysis/image
    volumes:
      - ./analysis/srv:/srv

  api:
    build: ./api/image
    hostname: api
    command: python3 api.py
    volumes:
      - ./api/srv/:/srv
      - ./analysis/srv/files/:/files:ro
    expose:
      - 8001
    networks:
      - localnet

  app:
    build: ./app
    ports:
      - "5173:5173"
      - "24678:24678"
    depends_on:
      - api
    volumes:
      - ./app/srv/mobydick/src:/srv/src
    networks:
      - localnet

  web:
    image: nginx:1.23-alpine
    hostname: web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - localnet

networks:
  localnet:
    driver: bridge