version: "3"
services:

  analysis:
    build: ./analysis/image
    volumes:
      - ./analysis/srv:/srv
    networks:
      - localnet

  # api:

  # app:

  # web:

networks:
  localnet:
    driver: bridge